### ISSUE TITLE
suggestion about "node build --copy"

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/ext-template#2]
This is the first time I use this fantastic tool for extension improvement, 

I suggest to make the copy **from site to src**, 

If you agree with me and not have the time I make PR, 

Best Regards

**Comment by yurikuzn** [comment]
Hi,

Do you mean to copy js files from `site/client/src` to `src`? I thought about this when wrote this tool and decided not to implement it. To encourage one-way process rather than bi-directional. To make things more simple and decrease chances of making mistake.

Regards

**Comment by eymen-elkum** [comment]
Yes that is what I mean, I wonder if implementing "watch" task over the `src` folder can help, so any change will automatically copied to the `site`

**Comment by eymen-elkum** [comment]
I found this tool: 
https://github.com/paulmillr/chokidar
> A neat wrapper around Node.js fs.watch / fs.watchFile / FSEvents.

I tested it, it is perfect!
