### ISSUE TITLE
Using other php packages that depends on "psr/log": "^1.0 || ^2.0 || ^3.0" creates a conflict

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/ext-template#23]
Currently trying to use mpdf package as a pdfengine however i am facing a problem because mpdf require "psr/log": "^1.0 || ^2.0 || ^3.0" while espocrm require only "psr/log": "1.1.*". This leads to a conflict. 

Any chance to require "psr/log": "^1.0" instead ? 

Thanks

**Comment by arkadiyasuratov** [comment]
You can try using "replace" property in composer.json, something like

```json
{
    "replace": {
        "psr/log": "*"
    }
}
```

**Comment by rabiibrahimi** [comment]
I tried that before but didn't work.

**Comment by yurikuzn** [comment]
Not related to ext-template. We update it in the future along with monolog, when we drop PHP 8.0.
