### ISSUE TITLE
Typo in schema - fileMatch and url for mapProviders

### ISSUE THREAD

**Issue by bandtank** [espocrm/ext-template#24]
See here: https://github.com/espocrm/ext-template/commit/eff9d45ea25fc6440bc8d9bbe70532bd80f43d9a#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357R365

I believe that should be mapProviders instead of mapPproviders. This linke does not work:
```
https://raw.githubusercontent.com/espocrm/espocrm/master/schema/metadata/app/mapPproviders.json
```

However, this link does work:
```
https://raw.githubusercontent.com/espocrm/espocrm/master/schema/metadata/app/mapProviders.json
```

I assume the filematch argument also needs to be tweaked to remove the extra p.

**Comment by yurikuzn** [comment]
Fixed. Thanks for reporting.
