### ISSUE TITLE
Port value in config-default.json is not used

### ISSUE THREAD

**Issue by bandtank** [espocrm/ext-template#26]
The initial configuration does not copy every field from `config-default.json`.  Specifically, if the database port is 3307 instead of 3306, for example, the installation will fail at `merge_configs.php`.

With this configuration:
```
    "database": {
        "host": "127.0.0.1",
        "port": "3307",
        "charset": "utf8mb4",
        "dbname": "ext-test-extension",
        "user": "root",
        "password": "root"
    },
```

This is what showed up in the Espo log:
```
[2024-05-22 19:21:35] ERROR: Uncaught Exception PDOException: "SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at ...
```

However, this works:
```
    "database": {
        "host": "127.0.0.1:3307",
        "port": "",
        "charset": "utf8mb4",
        "dbname": "ext-test-extension",
        "user": "root",
        "password": "root"
    },
```

`build.js` in `espocrm-extension-tools` does not explicitly use the port value:
```
        cp.execSync(
            "php install/cli.php -a setupConfirmation -d \"host-name=" + config.database.host +
            "&db-name=" + config.database.dbname +
            "&db-platform=" + dbPlatform +
            "&db-user-name=" + config.database.user +
            "&db-user-password=" + config.database.password + "\"",
            {cwd: cwd + '/site'}
        );
```

It is confusing for the `port` setting to be included in `config-default.json` if it is not actually used in the PHP setup files. E.g. from `setupConfirmation.php`:
```
$dbConfig = [
    'host' => $hostData[0] ?? '',
    'port' => $hostData[1] ?? '',
    'dbname' => $installData['db-name'],
    'user' => $installData['db-user-name'],
    'password' => $installData['db-user-password'],
    'platform' => $installData['db-platform'] ?? null,
];
```

I would expect there to be fields called `db-host` and `db-port` or for the `port` field to be removed from `config-default.json`.

**Comment by yurikuzn** [comment]
Concatenating host and port should solve the problem: https://github.com/espocrm/extension-tools/commit/84196f3bf71ce2f6c90a7522ada7094958a85867
