### ISSUE TITLE
Error when build in ext-template

### ISSUE THREAD

**Issue by farhadlavaei** [espocrm/ext-template#7]
After i clone the ext-template , when run the "node build --all", have this error:
$ node build --all
Fetching EspoCRM repository...
  Downloading EspoCRM archive from Github...
  Unzipping...
Installing EspoCRM instance...
  Creating config...
  Npm install...
  Building...
  Install: step1...
  Install: setupConfirmation...
  Install: checkPermission...
  Install: saveSettings...
  Install: buildDatabase...
  Install: createUser...
  Install: finish...
  Merge configs...
(node:18720) UnhandledPromiseRejectionWarning: Error: Command failed: php merge_configs.php
    at checkExecSyncError (child_process.js:643:11)
    at Object.execSync (child_process.js:679:15)
    at D:\xampp\htdocs\projects\ext_prifix\build.js:197:12
    at new Promise (<anonymous>)
    at install (D:\xampp\htdocs\projects\ext_prifix\build.js:139:12)
    at D:\xampp\htdocs\projects\ext_prifix\build.js:18:15
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promis
e which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_u
nhandled_rejections_mode). (rejection id: 2)
(node:18720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zer
o exit code.

**Comment by yurikuzn** [comment]
Check the log in `site/data/log`.

**Comment by farhadlavaei** [comment]
I apologize. It was my fault. The relevant database was not created.
Thank you
